# Site settings
title:       tomgalvin.uk
author:      Thomas Galvin
email:
contact_email: contact@tomgalvin.uk
description: "My thoughts on the world of programming, computer science and technology"
baseurl:     ""
url:         "https://tomgalvin.uk"
enforce_ssl: "tomgalvin.uk"
plugins: [jekyll-paginate]

# Google analytics
google_analytics: UA-57985829-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
disqus_shortname: usnpw

# Social icons
show_social_icons: true
github_username: tom-galvin
stackoverflow_profile_id: 4325617
twitter_username:
google_plus_id:
linkedin_username: tomgalvin97
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     4
sass:
compressed: true
