# Site settings
title:       username.password
email:       tom+site@usn.pw
author:      Thomas Galvin
description: "My thoughts on the world of programming, computer science and technology"
baseurl:     ""
url:         "http://usn.pw"

# Google analytics
google_analytics: UA-57985829-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
disqus_shortname: usnpw

# Social icons
show_social_icons: true
github_username: Quackmatic
stackoverflow_profile_id: 4325617
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
